/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appadmin;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jeanpi03
 */
public class PanelListarInmuebles extends javax.swing.JPanel {

    /**
     * Creates new form PanelListarInmuebles
     */
    public PanelListarInmuebles() {
        initComponents();
        initStyles();
    }

    private void initStyles() {
        titulo.putClientProperty("FlatLaf.styleClass", "h1");

    }

    private void showTable(JPanel p) {

        p.setSize(750, 292);
        p.setLocation(0, 0);

        Rbusqueda.removeAll();
        Rbusqueda.add(p, BorderLayout.CENTER);
        Rbusqueda.revalidate();
        Rbusqueda.repaint();
    }

    private void listarPorfecha() {
        String dia = txfDia.getText();
        String mes = txfMes.getText();
        String año = txfAño.getText();
        String fecha = dia + "/" + mes + "/" + año.trim();
        boolean fdateCorrect = false;
        boolean formatDate = false;
        boolean dateCorrect = false;

        if (dia.equals("DD")
                || dia.equals("")
                || mes.equals("MM")
                || mes.equals("")
                || año.equals("AAAA")
                || año.equals("")) {
            fdateCorrect = false;
        }

        //comprobar formato de fecha
        if (dia.length() == 2 && mes.length() == 2 && año.length() == 4) {
            formatDate = true;
        }

        if (!formatDate) {
            JOptionPane.showMessageDialog(null, "Ingresar fecha en formato correcto (DD/MM/AAAA)");
        }
        //verificar fecha
        DateValidation vfecha = null;
        if (fdateCorrect && formatDate) {
            vfecha = vfecha.verificarFecha(dia, mes, año);
            dateCorrect = vfecha.isValid();
        }
        
        if (!dateCorrect && fdateCorrect) {
            JOptionPane.showMessageDialog(null, vfecha.getMessage());
        }
        
        if(dateCorrect){
            showTable(new TablaBusquedaFF(fecha));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnDesocupados = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        jlBtn1 = new javax.swing.JLabel();
        jlBtn2 = new javax.swing.JLabel();
        jlBtn3 = new javax.swing.JLabel();
        btnId = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Rbusqueda = new javax.swing.JPanel();
        txfDia = new javax.swing.JTextField();
        txfMes = new javax.swing.JTextField();
        txfAño = new javax.swing.JTextField();

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda-de-casa (1).png"))); // NOI18N
        titulo.setText("BÚSQUEDA DE INMUEBLES");

        btnDesocupados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cheque.png"))); // NOI18N
        btnDesocupados.setText("Desocupados");
        btnDesocupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesocupadosActionPerformed(evt);
            }
        });

        btnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entrega.png"))); // NOI18N
        btnFecha.setText("Buscar por fecha");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        jlBtn1.setForeground(new java.awt.Color(102, 0, 0));
        jlBtn1.setText("<html> Presione este botón para <br>listar los inmuebles desocupados <html>");

        jlBtn2.setForeground(new java.awt.Color(102, 0, 0));
        jlBtn2.setText("<html>listar los inmuebles<br> facturados en una fecha dada<br> Rellenar el campo con la fecha!!  <html>");

        jlBtn3.setForeground(new java.awt.Color(102, 0, 0));
        jlBtn3.setText("<html>listar los inmuebles facturados <br> por persona y sus costos<br>Rellenar el campo de ID<html>");

        btnId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personas.png"))); // NOI18N
        btnId.setText("Buscar por ID");

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Ingresar ID");

        Rbusqueda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RbusquedaLayout = new javax.swing.GroupLayout(Rbusqueda);
        Rbusqueda.setLayout(RbusquedaLayout);
        RbusquedaLayout.setHorizontalGroup(
            RbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        RbusquedaLayout.setVerticalGroup(
            RbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        txfDia.setText("DD");
        txfDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txfDiaMousePressed(evt);
            }
        });

        txfMes.setText("MM");
        txfMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txfMesMousePressed(evt);
            }
        });

        txfAño.setText("AAAA");
        txfAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txfAñoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(txfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Rbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnDesocupados, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDesocupados)
                    .addComponent(btnFecha)
                    .addComponent(btnId))
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rbusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesocupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesocupadosActionPerformed
        showTable(new TablaIDesocupados());
    }//GEN-LAST:event_btnDesocupadosActionPerformed

    private void txfDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfDiaMousePressed
        txfDia.setText("");
    }//GEN-LAST:event_txfDiaMousePressed

    private void txfMesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfMesMousePressed
        txfMes.setText("");
    }//GEN-LAST:event_txfMesMousePressed

    private void txfAñoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfAñoMousePressed
        txfAño.setText("");
    }//GEN-LAST:event_txfAñoMousePressed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        listarPorfecha();
    }//GEN-LAST:event_btnFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Rbusqueda;
    private javax.swing.JButton btnDesocupados;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnId;
    private javax.swing.JPanel contenido;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlBtn1;
    private javax.swing.JLabel jlBtn2;
    private javax.swing.JLabel jlBtn3;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txfAño;
    private javax.swing.JTextField txfDia;
    private javax.swing.JTextField txfMes;
    // End of variables declaration//GEN-END:variables
}
