/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appadmin;

import javax.swing.JOptionPane;

/**
 *
 * @author jeanpi03
 */
public class PanelRegistroC extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroC
     */
    public PanelRegistroC() {
        initComponents();
        initStyles();
    }

    private void initStyles() {
        Rlabel.putClientProperty("FlatLaf.styleClass", "h1");
    }

    private void registrarCLientes() {
        String id = txfDocumento.getText();
        String name = txfName.getText();
        String correo = txfCorreo.getText();
        String direccion = txfDireccion.getText();
        String telefono = txfTelefono.getText();

        boolean fieldCorrect = false;
        if (id.length() != 0
                && direccion.length() != 0
                && telefono.length() != 0
                && name.length() != 0
                && correo.length() != 0) {

            fieldCorrect = true;
        }

        if (!fieldCorrect) {
            JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campos!!!");
        }

        //////////////////////////////////////AÑADIDO/////////////////////////////////////////////////////////////       
        //Evaluacion de campos (ID, nombre, telefono y correo)
        boolean nameIDcorrect = false;
        boolean tieneletram = false;
        char lm;
        boolean emailCorrect = false;
        boolean emailpunto = false;
        boolean emailarroba = false;
        if (fieldCorrect) {
            for (int i = 0; i < id.length(); i++) {
                lm = id.charAt(i);
                if (lm >= 'a' && lm <= 'z') {
                    tieneletram = true;
                }
            }
            boolean tieneletraM = false;
            char lM;
            for (int i = 0; i < id.length(); i++) {
                lM = id.charAt(i);
                if (lM >= 'A' && lM <= 'Z') {
                    tieneletraM = true;
                }
            }

            if (tieneletram || tieneletraM) {
                JOptionPane.showMessageDialog(null, "El ID no debe contener letras");
            }

            boolean tieneNumero = false;
            char c;
            //Comprobar dígito
            for (int i = 0; i < name.length(); i++) {
                c = name.charAt(i);
                if (c >= '0' && c <= '9') {
                    tieneNumero = true;
                }
            }

            if (tieneNumero) {
                JOptionPane.showMessageDialog(null, "El nombre no debe contener numeros");
            }

            boolean tlfLetram = false;
            char tlfm;
            for (int i = 0; i < telefono.length(); i++) {
                tlfm = telefono.charAt(i);
                if (tlfm >= 'a' && tlfm <= 'z') {
                    tlfLetram = true;
                }
            }
            boolean tlfLetraM = false;
            char tlfM;
            for (int i = 0; i < telefono.length(); i++) {
                tlfM = telefono.charAt(i);
                if (tlfM >= 'A' && tlfM <= 'Z') {
                    tlfLetraM = true;
                }
            }

            if (tlfLetram || tlfLetraM) {
                JOptionPane.showMessageDialog(null, "El numero de telefono no debe contener letras");
            }

            if (!tieneletram && !tieneletraM && !tieneNumero && !tlfLetram && !tlfLetraM) {
                nameIDcorrect = true;
            }

            char email;
            for (int i = 0; i < correo.length(); i++) {
                email = correo.charAt(i);
                if (email == '@') {
                    emailarroba = true;
                }
                if (email == '.') {
                    emailpunto = true;
                }
            }

            if (emailarroba && emailpunto) {
                emailCorrect = true;
            }

            if (!emailCorrect) {
                JOptionPane.showMessageDialog(null, "El correo debe tener punto '.' y arroba '@'");
            }
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////   

        if (fieldCorrect && nameIDcorrect && emailCorrect) {
            Cliente.saveCliente(id, name, correo, direccion, telefono);
            txfDocumento.setText("");
            txfName.setText("");
            txfCorreo.setText("");
            txfDireccion.setText("");
            txfTelefono.setText("");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Rlabel = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        txfDocumento = new javax.swing.JTextField();
        RjLabelName1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RjLabelName = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        txfTelefono = new javax.swing.JTextField();
        jltelefono = new javax.swing.JLabel();
        registroCorreo2 = new javax.swing.JLabel();
        txfCorreo = new javax.swing.JTextField();
        registroDireccion2 = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 490));

        Rlabel.setText("REGISTRO DE CLIENTES");

        txfName.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        txfName.setForeground(new java.awt.Color(0, 0, 0));
        txfName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txfDocumento.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        txfDocumento.setForeground(new java.awt.Color(0, 0, 0));
        txfDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RjLabelName1.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        RjLabelName1.setForeground(new java.awt.Color(0, 0, 0));
        RjLabelName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        RjLabelName1.setText("Nombre");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RjLabelName.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        RjLabelName.setForeground(new java.awt.Color(0, 0, 0));
        RjLabelName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-identificacion.png"))); // NOI18N
        RjLabelName.setText("Documento");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-interface.png"))); // NOI18N

        txfTelefono.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        txfTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jltelefono.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jltelefono.setForeground(new java.awt.Color(0, 0, 0));
        jltelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llamada-telefonica.png"))); // NOI18N
        jltelefono.setText("Teléfono");

        registroCorreo2.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        registroCorreo2.setForeground(new java.awt.Color(0, 0, 0));
        registroCorreo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar-correo.png"))); // NOI18N
        registroCorreo2.setText("Correo electronico");

        txfCorreo.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        txfCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCorreoActionPerformed(evt);
            }
        });

        registroDireccion2.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        registroDireccion2.setForeground(new java.awt.Color(0, 0, 0));
        registroDireccion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.png"))); // NOI18N
        registroDireccion2.setText("Dirección");

        txfDireccion.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        txfDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registroDireccion2)
                                    .addComponent(jltelefono))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registroCorreo2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RjLabelName)
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(RjLabelName1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rlabel)
                .addGap(0, 270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Rlabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RjLabelName)
                    .addComponent(txfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RjLabelName1)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroCorreo2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltelefono)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarCLientes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCorreoActionPerformed

    private void txfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RjLabelName;
    private javax.swing.JLabel RjLabelName1;
    private javax.swing.JLabel Rlabel;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jltelefono;
    private javax.swing.JLabel registroCorreo2;
    private javax.swing.JLabel registroDireccion2;
    private javax.swing.JTextField txfCorreo;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfDocumento;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
}
