/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appadmin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeanpi03
 */
public class TablaBusquedaFF extends javax.swing.JPanel {

    /**
     * Creates new form TablaBusquedaFF
     */
    public TablaBusquedaFF(long id) {
        initComponents();
        initTableId(id);
    }
    boolean foundid;
    private void initTableId(long id) {
        model = (DefaultTableModel) this.jTable1.getModel();
        Factura[] facturas = Factura.loadFacturas();
        for (Factura factura : facturas) {
            if (id==factura.getId()) {
                foundid=true;
                model.addRow(new Object[]{
                factura.getTransaccion(),
                factura.getName(),
                factura.getId(),
                factura.getDireccion(),
                factura.getFecha(),
                "$"+factura.getCosto()});
            }
        }
        
        if(!foundid){
            JOptionPane.showMessageDialog(null, "No se encontraron facturas de la persona con id: " + id);
        }
    }
    
    
    
    
    public TablaBusquedaFF(String fecha) {
        initComponents();
        initTableFecha(fecha);
    }
    DefaultTableModel model;
    boolean foundfecha=false;
    
    private void initTableFecha(String fecha) {
        model = (DefaultTableModel) this.jTable1.getModel();
        System.out.println("fecha ingresada para buscar: " + fecha);
        Factura[] facturas = Factura.loadFacturas();
        for (Factura factura : facturas) {
            if (fecha.equals(factura.getFecha())) {
                foundfecha=true;
                model.addRow(new Object[]{
                factura.getTransaccion(),
                factura.getName(),
                factura.getId(),
                factura.getDireccion(),
                factura.getFecha(),
                "$"+factura.getCosto()});
            }
        }
        
        if(!foundfecha){
            JOptionPane.showMessageDialog(null, "No se encontraron facturas de la fecha ingresada!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaccion", "Nombre", "Documento", "Inmuebles", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
